# Generated by Django 6.0.5 on 2026-05-13 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=64)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('mid_grade_price', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('premium_price', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('diesel_price', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('price_per_gallon', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'city'], name='api_fuelpri_state_ca6b9a_idx')],
                'constraints': [models.UniqueConstraint(fields=('latitude', 'longitude'), name='uniq_fuelprice_lat_long')],
            },
        ),
    ]
